language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install squizlabs/php_codesniffer

script:
  - vendor/bin/phpcs --standard=PSR2 -n application/libraries/Sentry/
