language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 -n application/libraries/Sentry/
  - vendor/bin/phpcs --standard=PSR2 -n application/modules/Sentry/
