#!/bin/bash

SE_PATH="./../"

rm -rf ./phpv4-sentry-master/
unzip ./phpv4-sentry.zip -d ./

rm -rf $SE_PATH/libraries/Sentry/
rm -rf $SE_PATH/modules/Sentry/

mv ./phpv4-sentry-master/application/modules/Sentry/ $SE_PATH/modules/Sentry/
mv ./phpv4-sentry-master/application/libraries/Sentry/ $SE_PATH/libraries/Sentry/

rm -f ./phpv4-sentry.zip
rm -rf ./phpv4-sentry-master/

composer install -d $SE_PATH/libraries/Sentry/
